import type { Theme } from '~/types'

export const colors = {
  brand: {
    DEFAULT: 'var(--td-brand-color-7)',
    hover: 'var(--td-brand-color-6)',
    focus: 'var(--td-brand-color-2)',
    active: 'var(--td-brand-color-8)',
    disabled: 'var(--td-brand-color-3)',
    light: {
      DEFAULT: 'var(--td-brand-color-1)',
      hover: 'var(--td-brand-color-2)',
    },
    1: 'var(--td-brand-color-1)',
    2: 'var(--td-brand-color-2)',
    3: 'var(--td-brand-color-3)',
    4: 'var(--td-brand-color-4)',
    5: 'var(--td-brand-color-5)',
    6: 'var(--td-brand-color-6)',
    7: 'var(--td-brand-color-7)',
    8: 'var(--td-brand-color-8)',
    9: 'var(--td-brand-color-9)',
    10: 'var(--td-brand-color-10)',
  },
  warning: {
    DEFAULT: 'var(--td-warning-color-5)',
    hover: 'var(--td-warning-color-4)',
    focus: 'var(--td-warning-color-2)',
    active: 'var(--td-warning-color-6)',
    disabled: 'var(--td-warning-color-3)',
    light: {
      DEFAULT: 'var(--td-warning-color-1)',
      hover: 'var(--td-warning-color-2)',
    },
    1: 'var(--td-warning-color-1)',
    2: 'var(--td-warning-color-2)',
    3: 'var(--td-warning-color-3)',
    4: 'var(--td-warning-color-4)',
    5: 'var(--td-warning-color-5)',
    6: 'var(--td-warning-color-6)',
    7: 'var(--td-warning-color-7)',
    8: 'var(--td-warning-color-8)',
    9: 'var(--td-warning-color-9)',
    10: 'var(--td-warning-color-10)',
  },
  error: {
    DEFAULT: 'var(--td-error-color-6)',
    hover: 'var(--td-error-color-5)',
    focus: 'var(--td-error-color-2)',
    active: 'var(--td-error-color-7)',
    disabled: 'var(--td-error-color-3)',
    light: {
      DEFAULT: 'var(--td-error-color-1)',
      hover: 'var(--td-error-color-2)',
    },
    1: 'var(--td-error-color-1)',
    2: 'var(--td-error-color-2)',
    3: 'var(--td-error-color-3)',
    4: 'var(--td-error-color-4)',
    5: 'var(--td-error-color-5)',
    6: 'var(--td-error-color-6)',
    7: 'var(--td-error-color-7)',
    8: 'var(--td-error-color-8)',
    9: 'var(--td-error-color-9)',
    10: 'var(--td-error-color-10)',
  },
  success: {
    DEFAULT: 'var(--td-success-color-5)',
    hover: 'var(--td-success-color-4)',
    focus: 'var(--td-success-color-2)',
    active: 'var(--td-success-color-6)',
    disabled: 'var(--td-success-color-3)',
    light: {
      DEFAULT: 'var(--td-success-color-1)',
      hover: 'var(--td-success-color-2)',
    },
    1: 'var(--td-success-color-1)',
    2: 'var(--td-success-color-2)',
    3: 'var(--td-success-color-3)',
    4: 'var(--td-success-color-4)',
    5: 'var(--td-success-color-5)',
    6: 'var(--td-success-color-6)',
    7: 'var(--td-success-color-7)',
    8: 'var(--td-success-color-8)',
    9: 'var(--td-success-color-9)',
    10: 'var(--td-success-color-10)',
  },
  gray: {
    1: 'var(--td-gray-color-1)',
    2: 'var(--td-gray-color-2)',
    3: 'var(--td-gray-color-3)',
    4: 'var(--td-gray-color-4)',
    5: 'var(--td-gray-color-5)',
    6: 'var(--td-gray-color-6)',
    7: 'var(--td-gray-color-7)',
    8: 'var(--td-gray-color-8)',
    9: 'var(--td-gray-color-9)',
    10: 'var(--td-gray-color-10)',
    11: 'var(--td-gray-color-11)',
    12: 'var(--td-gray-color-12)',
    13: 'var(--td-gray-color-13)',
    14: 'var(--td-gray-color-14)',
  },
  font: {
    white: {
      1: 'var(--td-font-white-1)',
      2: 'var(--td-font-white-2)',
      3: 'var(--td-font-white-3)',
      4: 'var(--td-font-white-4)',
    },
    gray: {
      1: 'var(--td-font-gray-1)',
      2: 'var(--td-font-gray-2)',
      3: 'var(--td-font-gray-3)',
      4: 'var(--td-font-gray-4)',
    },
  },
  divider: 'var(--td-border-level-1-color)',
  border: 'var(--td-border-level-2-color)',
} satisfies Theme['colors']
