import type { Theme } from '~/types'

export const containers = {
  '1': 'var(--td-size-1)',
  '2': 'var(--td-size-2)',
  '3': 'var(--td-size-3)',
  '4': 'var(--td-size-4)',
  '5': 'var(--td-size-5)',
  '6': 'var(--td-size-6)',
  '7': 'var(--td-size-7)',
  '8': 'var(--td-size-8)',
  '9': 'var(--td-size-9)',
  '10': 'var(--td-size-10)',
  '11': 'var(--td-size-11)',
  '12': 'var(--td-size-12)',
  '13': 'var(--td-size-13)',
  '14': 'var(--td-size-14)',
  '15': 'var(--td-size-15)',
  '16': 'var(--td-size-16)',
  '3xs': 'var(--td-comp-size-xxxs)',
  '2xs': 'var(--td-comp-size-xxs)',
  'xs': 'var(--td-comp-size-xs)',
  's': 'var(--td-comp-size-s)',
  'm': 'var(--td-comp-size-m)',
  'l': 'var(--td-comp-size-l)',
  'xl': 'var(--td-comp-size-xl)',
  '2xl': 'var(--td-comp-size-xxl)',
  '3xl': 'var(--td-comp-size-xxxl)',
  '4xl': 'var(--td-comp-size-xxxxl)',
  '5xl': 'var(--td-comp-size-xxxxxl)',
} satisfies Theme['containers']
